# This file was automatically generated by bifcl from /build/securityonion-bro-bmYGD9/securityonion-bro-2.5.5/src/analyzer/protocol/rdp/types.bif (plugin mode).


export {
module RDP;




} # end of export section
module GLOBAL;
