# This file was automatically generated by bifcl from /build/securityonion-bro-bmYGD9/securityonion-bro-2.5.5/src/logging/writers/none/none.bif (plugin mode).




export {
module LogNone;



} # end of export section
module GLOBAL;
