# This file was automatically generated by bifcl from /build/securityonion-bro-bmYGD9/securityonion-bro-2.5.5/src/analyzer/protocol/smb/consts.bif (plugin mode).

export {
} # end of export section
module GLOBAL;
