# This file was automatically generated by bifcl from /build/securityonion-bro-bmYGD9/securityonion-bro-2.5.5/src/input/readers/sqlite/sqlite.bif (plugin mode).


export {
module InputSQLite;





} # end of export section
module GLOBAL;
