# This file was automatically generated by bifcl from /build/securityonion-bro-bmYGD9/securityonion-bro-2.5.5/src/analyzer/protocol/ssh/types.bif (plugin mode).

export {
module SSH;





module GLOBAL;
} # end of export section
module GLOBAL;
