# This file was automatically generated by bifcl from /build/securityonion-bro-bmYGD9/securityonion-bro-2.5.5/src/logging/writers/ascii/ascii.bif (plugin mode).




export {
module LogAscii;











} # end of export section
module GLOBAL;
