# This file was automatically generated by bifcl from /build/securityonion-bro-bmYGD9/securityonion-bro-2.5.5/src/logging/writers/sqlite/sqlite.bif (plugin mode).




export {
module LogSQLite;






} # end of export section
module GLOBAL;
