# This file was automatically generated by bifcl from /build/securityonion-bro-bmYGD9/securityonion-bro-2.5.5/src/input/readers/raw/raw.bif (plugin mode).


export {
module InputRaw;



} # end of export section
module GLOBAL;
