# This file was automatically generated by bifcl from /build/securityonion-bro-bmYGD9/securityonion-bro-2.5.5/src/analyzer/protocol/xmpp/events.bif (plugin mode).

## Generated when a XMPP connection goes encrypted after a successful
## StartTLS exchange between the client and the server.
##
## c: The connection.
export {
global xmpp_starttls: event(c: connection );

} # end of export section
module GLOBAL;
