# This file was automatically generated by bifcl from /build/securityonion-bro-bmYGD9/securityonion-bro-2.5.5/src/input/readers/ascii/ascii.bif (plugin mode).


export {
module InputAscii;








} # end of export section
module GLOBAL;
