# This file was automatically generated by bifcl from /build/securityonion-bro-bmYGD9/securityonion-bro-2.5.5/src/input/readers/binary/binary.bif (plugin mode).


export {
module InputBinary;



} # end of export section
module GLOBAL;
