# This file was automatically generated by bifcl from /build/securityonion-bro-bmYGD9/securityonion-bro-2.5.5/src/broker-dummy/store.bif (alternative mode).


##! Placeholder for Broker-based communication functionality, not enabled
##! by default
export {
} # end of export section
module GLOBAL;
